### ISSUE TITLE
add live demo please

### ISSUE THREAD

**Issue by aianshume** [swup/slide-theme#18]
its really hard to recognize what this this work for me please add a live demo for this so we see preview before installing, thank you

**Comment by godalming123-ipad** [comment]
you can add live demo with github pages:
1. go to the settings tab on the repo.
2. select pages from the sidebar on the left
3. change the value in the dropdown from none to whatever branch you want to host
4. you can also change the directory that the index.html file is in with the dropdown next the one mentioned above.
5.  click save and after about 2 minutes github will build your site when your site is built it will say your site is published at somewhere but it will actually take another 6 or so minutes to deploy than you can visit the link and see your changes.
![image](https://user-images.githubusercontent.com/68993177/130060472-1b277fba-7635-4c1d-abe6-5e22440fbd78.png)

**Comment by mevanloon** [comment]
The Swup docs have a demo integrated: https://swup.js.org/themes

**Comment by aianshume** [comment]
Thanks
