### ISSUE TITLE
Targeting other element than default #swup

### ISSUE THREAD

**Issue by jamesgillispie** [swup/slide-theme#3]
Using this option does not appear to be working

```
var swup = new Swup();
swup.usePlugin(SwupSlideTheme, {mainElement: '#another-element'}); 
```

Thanks, amazing amazing work

**Comment by gmrchk** [comment]
Hi and thanks!

I checked and `mainElement` option seems to work as expected. Also, this is not a valid syntax anymore. Swup doesn't have `usePlugin` method. 

Please check docs
https://swup.js.org/themes/slide-theme
https://swup.js.org/plugins
